	
		<p>&copy; 2025 MemMis. All rights reserved.</p>

		<br>
		<a href="https://trucnttkh.atlassian.net/jira/software/projects/MEMMIS/boards/34/backlog?atlOrigin=eyJpIjoiMzZiMzAwYmI1OTYyNDNjNDhlZDc2ZDk5OTI2NTFiYTgiLCJwIjoiaiJ9"
		   target="_blank">Jira Project for MemMis website ↗</a>

		<br><br>
		<a href="https://github.com/TrucNguyen106217880/MemMis_WebProject"
		   target="_blank">GitHub Repository ↗</a>
	