	
		<p>&copy; 2025 MemMis. All rights reserved.</p>

		<br>
		<a href="https://trucnttkh.atlassian.net/jira/software/projects/MEMMIS/boards/34/backlog?atlOrigin=eyJpIjoiMzZiMzAwYmI1OTYyNDNjNDhlZDc2ZDk5OTI2NTFiYTgiLCJwIjoiaiJ9"
		   target="_blank" class="external_link">Jira Project for MemMis website</a>
		<a href="https://github.com/TrucNguyen106217880/MemMis_WebProject"
		   target="_blank" class="external_link">GitHub Repository</a>

		<br><br>
		<a href='manage.php' class='internal_link'>Go to Management page</a>

		<br><br>
		<a href='enhancements.php' class='internal_link'>Website enhancements logs</a>