<input type="checkbox" id="menu_toggle" tabindex="0" title="Toggle menu">
	<span id="menu_toggle_tip">Spacebar to toggle menu</span>
	<header>
		<!-- This logo was created using a text-to-image AI tool provided by Canva, with modifications toward quality -->
		<img id="logo" src="images/MemMis_Logo.png"
			 title="Custom Website Design & Development | MemMis"
			 alt="MemMis logo" loading="lazy">
